version: '3.3'

services:

  db:
    image: postgres:14
    privileged: true
    environment:
      POSTGRES_PASSWORD: Root@1998
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  minio:
    image: docker.io/bitnami/minio:2023
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Root@1998
    volumes:
      - 'minio_data:/data'

volumes:
  minio_data:
    driver: local
